import ftyp from './ftyp';
import mvhd from './mvhd';
import tkhd from './tkhd';
import elst from './elst';
import mdhd from './mdhd';
import hdlr from './hdlr';
import vmhd from './vmhd';
import dref from './dref';
import url from './url';
import stsd from './stsd';
import avc1 from './avc1';
import avcC from './avcC';
import stts from './stts';
import stss from './stss';
import ctts from './ctts';
import stsc from './stsc';
import stsz from './stsz';
import stco from './stco';
import smhd from './smhd';
import mp4a from './mp4a';
import esds from './esds';
import meta from './meta';
import mdat from './mdat';
import sdtp from './sdtp';
import thmb from './thmb';
declare const _default: {
    ftyp: typeof ftyp;
    mvhd: typeof mvhd;
    tkhd: typeof tkhd;
    elst: typeof elst;
    mdhd: typeof mdhd;
    hdlr: typeof hdlr;
    vmhd: typeof vmhd;
    dref: typeof dref;
    'url ': typeof url;
    stsd: typeof stsd;
    avc1: typeof avc1;
    avcC: typeof avcC;
    stts: typeof stts;
    stss: typeof stss;
    ctts: typeof ctts;
    stsc: typeof stsc;
    stsz: typeof stsz;
    stco: typeof stco;
    smhd: typeof smhd;
    mp4a: typeof mp4a;
    esds: typeof esds;
    meta: typeof meta;
    mdat: typeof mdat;
    sdtp: typeof sdtp;
    thmb: typeof thmb;
};
export default _default;
